// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentMgt_EF.Data;

#nullable disable

namespace StudentMgt_EF.Migrations
{
    [DbContext(typeof(DbContextClass))]
    [Migration("20240513055053_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentMgt_EF.ModelEntity.Student", b =>
                {
                    b.Property<int>("Student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_id"));

                    b.Property<int>("Student_age")
                        .HasColumnType("int");

                    b.Property<string>("Student_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Student_id");

                    b.ToTable("newStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
